class Ajustes:
    def __init__(self, UMBRAL_NEGRO: int = 200, FRACCION_MINIMA_PIXELES_NEGROS: float = 3/4, SIZE_PENTAGRAMA_IDEAL:int = 43, DETECTAR_CORCHEAS:bool = False, CAMBIAR_SIZE: bool = False, PORCENTAJE_DETECTAR_NOTA:float = 0.45, PORCENTAJE_DIFERENCIAR_NEGRA_BLANCA:float = 0.65):
        self.UMBRAL_NEGRO: int = UMBRAL_NEGRO
        self.FRACCION_MINIMA_PIXELES_NEGROS: float = FRACCION_MINIMA_PIXELES_NEGROS
        self.SIZE_PENTAGRAMA_IDEAL:int = SIZE_PENTAGRAMA_IDEAL
        self.DETECTAR_CORCHEAS:bool = DETECTAR_CORCHEAS
        self.CAMBIAR_SIZE:bool = CAMBIAR_SIZE
        self.PORCENTAJE_DETECTAR_NOTA:float = PORCENTAJE_DETECTAR_NOTA
        self.PORCENTAJE_DIFERENCIAR_NEGRA_BLANCA:float = PORCENTAJE_DIFERENCIAR_NEGRA_BLANCA